### ISSUE TITLE
Switching between faster-whisper or openai-whisper via env seems to be broken #edit: most likely not, just not as fast as I hoped for

### ISSUE THREAD

**Issue by Deathproof76** [ahmetoner/whisper-asr-webservice#115]
I transcribed a 22 minute mp3 file with - ASR_ENGINE=openai_whisper via the webui, timed it and it took 2:15 min. I then changed the env to - ASR_ENGINE=faster_whisper, recreated the container and it took approximately the same 2:16 min. Tried another file with the same outcome. Switched to :debug, also the same outcome. Vram consumption is also much higher than expected for faster-whisper, but in line with openai-whisper.

```
services:
  whisper-asr-webservice:
    #image: onerahmet/openai-whisper-asr-webservice:debug-gpu
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    container_name: Whisper-ASR
    environment:
      - ASR_ENGINE=openai_whisper
#      - ASR_ENGINE=faster_whisper
      - ASR_MODEL=small
    ports:
      - 9007:9000
    restart: unless-stopped
```

Would be glad if you could take a look at it @ahmetoner, as it seems to be broken.

Also described by other people https://github.com/morpheus65535/bazarr/issues/2144

I don't know much, but it seems possible that the downloaded openai-whisper model isn't converted to the CTranslate2 model format. If that is the case, wouldn't it be possible to just download the model directly from https://huggingface.co/guillaumekln/faster-whisper-small (as an example)? 

Or could it be that the wrong model is selected? Instead of loading the converted model, the openai-whisper model is loaded?

Another possibility could be that the settings differ between OpenAI-whisper and faster-whisper: Depending on the gpu fp16 could be a lot faster than fp32 https://github.com/openai/whisper/discussions/391 . Also beam_size https://github.com/guillaumekln/faster-whisper/issues/9 https://github.com/guillaumekln/faster-whisper/issues/172 and temperature https://github.com/guillaumekln/faster-whisper/issues/172
If these options are the reason for "underperforming" would it be possible to expose them as env variables for the docker container? (@ayancey)
