### ISSUE TITLE
Strange bug when migrating from 1.4.1-gpu to 1.7.1-gpu

### ISSUE THREAD

**Issue by flefevre** [ahmetoner/whisper-asr-webservice#273]
When i upload a large file (>18mo) with ASR_MODEL=large-v3-turbo and ASR_ENGINE=faster_whisper 
I get 
```Server response
Code	Details
Undocumented
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
```

that i do not have with the 1.4.1-gpu

any idea if i need to change something in the Dockerfile or docker-compose.yml ?

*Dockerfile
```
FROM onerahmet/openai-whisper-asr-webservice:v1.7.1-gpu
```

*docker-compose.yml

```
# Audio Speech Recognition, 
# https://ahmetoner.com/whisper-asr-webservice/run/ 

networks:
  # réseau utilisé par Traefik pour router les requêtes vers les service exposés à l'exterieur
  traefik_network:
    external: true

volumes:
  whispercache:
  huggingfacecache:
  filebrowser-config:

services:
  fasterwhisperasrwebservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fasterwhisperasrwebservice
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      #- whispercache:/root/.cache/whisper
      - ./models:/root/.cache/whisper
    environment:
      - TZ=Europe/Paris
      - DEVICEIDS=${DEVICEIDS}
      - ASR_MODEL=${ASR_MODEL}
      - ASR_ENGINE=${ASR_ENGINE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.fasterwhisperasrwebservice.rule=Host(`fasterwhisperasrwebservice.${DOMAIN}`)
      - traefik.http.routers.fasterwhisperasrwebservice.tls=true
      - traefik.http.services.fasterwhisperasrwebservice.loadbalancer.server.port=9000
      
      #to add for cors
      # - traefik.enable=true
      # - traefik.http.routers.fasterwhisperasrwebservice.rule=Host(`fasterwhisperasrwebservice.${DOMAIN}`)
      # - traefik.http.routers.fasterwhisperasrwebservice.tls=true
      # - traefik.http.middlewares.fasterwhisperasrwebservice-cors.headers.accesscontrolalloworigin=*
      # - traefik.http.middlewares.fasterwhisperasrwebservice-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE
      # - traefik.http.middlewares.fasterwhisperasrwebservice-cors.headers.accesscontrolallowheaders=Content-Type,Authorization
      # - traefik.http.middlewares.fasterwhisperasrwebservice-cors.headers.accesscontrolallowcredentials=true
      # - traefik.http.routers.fasterwhisperasrwebservice.middlewares=fasterwhisperasrwebservice-cors
    # expose:
    #   - 9000
    # ports:
    #   - 9000:9000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${DEVICEIDS}']
              #count: 1
              capabilities: [gpu]
              #capabilities: [compute, utility]
  
  #hack to copy/paste easily the models even if no whitelist added
  #https://github.com/hurlenko/filebrowser-docker
  filebrowser:
    image: hurlenko/filebrowser
    container_name: fasterwhisperasrwebservice-filebrowser
    restart: unless-stopped
    networks:
      traefik_network:
    volumes:
      #- whispercache:/data
      - ./models:/data
      - filebrowser-config:/config
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.enable=true
      - traefik.http.routers.fasterwhisperasrwebservice-filebrowser.rule=Host(`fasterwhisperasrwebservice-filebrowser.${DOMAIN}`)
      - traefik.http.routers.fasterwhisperasrwebservice-filebrowser.tls=true
      - traefik.http.services.fasterwhisperasrwebservice-filebrowser.loadbalancer.server.port=8080
    
```
