### ISSUE TITLE
WhisperX integration: quick question on model alignment version

### ISSUE THREAD

**Issue by flefevre** [ahmetoner/whisper-asr-webservice#289]
Hello,
I have tested latest version of whisper-asr-webservice, 1.8.2-gpu with 

```
ASR_MODEL=large-v3 
ASR_ENGINE=whisperx
```

**I have noticed the following logs:**

```
fasterwhisperasrwebservice              | Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
fasterwhisperasrwebservice              | Model was trained with torch 1.10.0+cu102, yours is 2.6.0+cu126. Bad things might happen unless you revert torch to 1.x.
```

Do I need to change something to align model version ?
Is there a way not to use model *pt which are not safe since they can add code section  and to priviledged *.Safetensors formatting instead ?
Is there any Environmental variable to ensure they are downloading in the right docker volume?

Notabene: whisperx is functionnial and it is cool >> **THANKS A LOT**

```
[SPEAKER_02]: Et si ce n'est pas bon, ils vont se faire allumer et ça va être dommageable pour eux.
[SPEAKER_01]: Ça, ce qui est clair pour nous, c'est qu'on partage le fait que la conclusion de fin d'année dernière n'était pas à un niveau de maturité suffisante.
```

**full docker starting log:**

```
 ✔ Container fasterwhisperasrwebservice              Recreated                                                                                                                     0.3s 
 ✔ Container fasterwhisperasrwebservice-filebrowser  Recreated                                                                                                                     0.0s 
Attaching to fasterwhisperasrwebservice, fasterwhisperasrwebservice-filebrowser
fasterwhisperasrwebservice-filebrowser  | 2025/02/18 06:48:07 Using database: /config/filebrowser.db
fasterwhisperasrwebservice-filebrowser  | 2025/02/18 06:48:07 No config file used
fasterwhisperasrwebservice-filebrowser  | 2025/02/18 06:48:07 Listening on 0.0.0.0:8080
fasterwhisperasrwebservice              | INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
fasterwhisperasrwebservice              | INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
Downloading config.json: 100%|██████████| 2.39k/2.39k [00:00<00:00, 4.99MB/s]
Downloading (…)rocessor_config.json: 100%|██████████| 340/340 [00:00<00:00, 255kB/s]
Downloading tokenizer.json: 100%|██████████| 2.48M/2.48M [00:00<00:00, 9.08MB/s]
Downloading vocabulary.json: 100%|██████████| 1.07M/1.07M [00:00<00:00, 1.84MB/s]
Downloading model.bin: 100%|██████████| 3.09G/3.09G [02:40<00:00, 19.2MB/s]5MB/s]
fasterwhisperasrwebservice              | Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.5.0.post0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .venv/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
fasterwhisperasrwebservice              | No language specified, language will be first be detected for each audio file (increases inference time).
fasterwhisperasrwebservice              | Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
fasterwhisperasrwebservice              | Model was trained with torch 1.10.0+cu102, yours is 2.6.0+cu126. Bad things might happen unless you revert torch to 1.x.
Downloading config.yaml: 100%|██████████| 469/469 [00:00<00:00, 347kB/s]
Downloading pytorch_model.bin: 100%|██████████| 5.91M/5.91M [00:00<00:00, 6.01MB/s]
Downloading config.yaml: 100%|██████████| 399/399 [00:00<00:00, 356kB/s]
Downloading pytorch_model.bin: 100%|██████████| 26.6M/26.6M [00:02<00:00, 11.5MB/s]
Downloading config.yaml: 100%|██████████| 221/221 [00:00<00:00, 174kB/s]
fasterwhisperasrwebservice              | INFO:     Started server process [7]
fasterwhisperasrwebservice              | INFO:     Waiting for application startup.
fasterwhisperasrwebservice              | INFO:     Application startup complete.
fasterwhisperasrwebservice              | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

**Comment by flefevre** [comment]
Where are downloaded the different models, transformers with pyannote and with what environmental variable the localtion is managed? As I do not have internet on the server, I need to preload the application and the models and copy/paste them in the production environment.

```
/root/.cache/whisper
PYANNOTE_CACHE:?
HF_HOME:?
TRANSFORMERS_CACHE: is this one old version of HF_HOME?
```

**Comment by flefevre** [comment]
I have solved the problem
Here the example to help other facing the same issue as me:

```
volumes:
  cache-pyannote:
  cache-torch:
  cache-whisper:

fasterwhisperasrwebservice:
    build:
      context: ./
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    volumes:
      - cache-pyannote:/root/.cache/pyannote
      - cache-torch:/root/.cache/torch
      - cache-whisper:/root/.cache/whisper
    environment:
      - ASR_MODEL=${ASR_MODEL}
      - ASR_ENGINE=${ASR_ENGINE}
      - HF_TOKEN=${HF_TOKEN}
      - ASR_DEVICE=cuda
      - ASR_MODEL_PATH=/root/.cache/whisper
      - PYANNOTE_CACHE=/root/.cache/pyannote
      - HF_HOME=/root/.cache/whisper

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              #count: 1
              capabilities: [gpu]
              #capabilities: [compute, utility]
```
