### ISSUE TITLE
Fresh docker installation - No module named 'app.webservice'

### ISSUE THREAD

**Issue by kikearciniegas** [ahmetoner/whisper-asr-webservice#308]
While trying to get this docker container running, it fails and gives this error in the logs:

```
Traceback (most recent call last):
  File "/app/.venv/bin/whisper-asr-webservice", line 3, in <module>
    from app.webservice import start
ModuleNotFoundError: No module named 'app.webservice'
```

This is my docker-compose.yaml file:

```
services:
  whisperasr:
    image: onerahmet/openai-whisper-asr-webservice:v1.8.2
    container_name: whisperasr
    networks:
      - avmedia
    environment:
      - ASR_DEVICE=cpu
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL=medium
      - ASR_MODEL_PATH=/data/whisper
    ports:
      - 9000:9000
    volumes:
      - /home/user/docker/whiperasr/app:/app/app
      - /home/user/docker/whiperasr/cache:/data/whisper
    restart: unless-stopped

networks:
  avmedia:
    external: true
```

Docker:

```
# docker version
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.23.8
 Git commit:        ce1223035ac3ab8922717092e63a184cf67b493d
 Built:             Sun Apr  6 12:16:07 2025
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       41ca978a0a5400cc24b274137efa9f25517fcc0b
  Built:            Sun Apr  6 12:16:07 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v2.0.0
  GitCommit:        207ad711eabd375a01713109a8a197d197ff6542
 runc:
  Version:          1.2.2
  GitCommit:        7cb363254b69e10320360b63fb73e0ffb5da7bf2
 docker-init:
  Version:          0.19.0
  GitCommit:
```

OS:

```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.21.3
PRETTY_NAME="Alpine Linux v3.21"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
docker:~/.docker/ct/portainer# 
```

How can I make this run without issues? Thanks in advance!

**Comment by kikearciniegas** [comment]
lol you are right.. i did change from alpine to ubuntu though...

**Comment by MRobi1** [comment]
Spinning up an Ubuntu container didn't work for me either. But disecting it piece by piece got me going.

The docker run command from docker hub works fine
```
docker run -d --gpus all -p 9000:9000 \
  -e ASR_MODEL=base \
  -e ASR_ENGINE=openai_whisper \
  onerahmet/openai-whisper-asr-webservice:latest-gpu
```

This docker-compose gives me the app.webservice error
```
---
name: whisper
services:
  whisper:
    ports:
      - 9000:9000
    environment:
      - ASR_DEVICE=cuda
      - ASR_MODEL=large-v3
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL_PATH=/data/whisper/cache
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - ./app:/app/app
      - /root/whisper/cache:/data/whisper/cache 
```

This docker-compose works
```
---
name: whisper
services:
  whisper:
    ports:
      - 9000:9000
    environment:
      - ASR_DEVICE=cuda
      - ASR_MODEL=large-v3
      - ASR_ENGINE=openai_whisper
      - ASR_MODEL_PATH=/data/whisper/cache
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - /root/whisper/cache:/data/whisper/cache 
```

As soon as a volume is defined for /app/app then the app.webservice error appears.
Which means the [example docker-compose files](https://raw.githubusercontent.com/ahmetoner/whisper-asr-webservice/refs/heads/main/docker-compose.gpu.yml) provided should be updated
