### ISSUE TITLE
Using Faster Whisper with Bazarr integration

### ISSUE THREAD

**Issue by MrSaiclops** [ahmetoner/whisper-asr-webservice#99]
Hello, 

I am running a Docker Container alongside Bazarr to generate subtitles for media that otherwise would not return a result. The compose looks like this:
```yaml
  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: Whisper
    environment:
      - ASR_MODEL=base
    ports:
      - 9000:9000
    restart: unless-stopped
   ```
  This was retrieved from here: https://github.com/bazarr/wiki/pull/201/files

It's working fine, but I would like to have it use faster-whisper. Is it doing so automatically or do I need to change something?

Thanks!

**Comment by Deathproof76** [comment]
You should repost here https://github.com/morpheus65535/bazarr/issues
even though it works, you need to look more closely in the docs. the maintainer of this repo most likely doesn't even know what bazarr is. the recommendation is to use the fork by @ayancey [alexyancey/openai-whisper-asr-webservice:latest](https://hub.docker.com/r/alexyancey/openai-whisper-asr-webservice) 
It's also very likely that the correct api call has to be issued from bazarrs side

**Comment by ahmetoner** [comment]
Hello @MrSaiclops, 

We will have a new release soon for faster-whisper. You will be able to run with an env variable. 

```yaml
  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: Whisper
    environment:
      - ASR_ENGINE=faster_whisper
      - ASR_MODEL=base
    ports:
      - 9000:9000
    restart: unless-stopped
   ```
